import pymiere
from pymiere.autogenerated.manuallyGenerated import Time

get_sequence = """var sequence = app.project.activeSequence;
var all_tracks = [];
for(var i=0; i<sequence.videoTracks.numTracks; i++){
    all_tracks.push(sequence.videoTracks[i]);
}
JSON.stringify(all_tracks)"""

if __name__== "__main__":
    PYMIERE = pymiere.Pymiere()
    sequence_info = PYMIERE.eval_script("$._pymiere['myFirstId'] = app.project.activeSequence; JSON.stringify($._pymiere['myFirstId']);")
    sequence = pymiere.objects.Sequence('myFirstId', name=sequence_info["name"], id=sequence_info["id"], videoTracks=sequence_info["videoTracks"])
    print(sequence.name)
    # print(sequence.id)
    # sequence.name = "nom sympa"
    # try:
    #     sequence.id = "caca"
    # except AttributeError:
    #     print("Id is read only check ok")
    print(sequence.getInPoint())
    # sequence.setPlayerPosition()
    # playerPos = sequence.getPlayerPosition()
    # print(playerPos)
    # print(playerPos.ticks)
    clip = sequence.videoTracks[0].clips[0]
    new_time = Time()
    new_time.seconds = 10

    print(new_time.ticks)

    clip.end = new_time