from pymiere.core import _eval_script_returning_object
from pymiere.autogenerated.premiere_objects import *

NaN = float(_eval_script_returning_object('NaN', as_kwargs=True))
Infinity = float(_eval_script_returning_object('Infinity', as_kwargs=True))
app = Application(**_eval_script_returning_object('app', as_kwargs=True))
document = Document(**_eval_script_returning_object('document', as_kwargs=True))
ProjectItemType = ProjectItemType(**_eval_script_returning_object('ProjectItemType', as_kwargs=True))
ScratchDiskType = ScratchDiskType(**_eval_script_returning_object('ScratchDiskType', as_kwargs=True))
RegisteredDirectories = RegisteredDirectories(**_eval_script_returning_object('RegisteredDirectories', as_kwargs=True))
UtilityFunctions = UtilityFunctions(**_eval_script_returning_object('UtilityFunctions', as_kwargs=True))
dollar = Dollar(**_eval_script_returning_object('$', as_kwargs=True))
Math = Math(**_eval_script_returning_object('Math', as_kwargs=True))
f = File(**_eval_script_returning_object('f', as_kwargs=True))

# todo use setter
# todo put functions